export const OFFSCREEN_PATH = 'src/offscreen/offscreen.html';
export const IDLE_ALARM = 'handsfree-idle';
export const WATCHDOG_ALARM = 'handsfree-command-timeout';
export const IDLE_MS = 3 * 60_000;
export const MAX_COMMAND_MS = 2 * 60_000;
export const MAX_LOG_ENTRIES = 30;
export interface CommandExample { group: string; text: string; hint: string; variations?: readonly string[]; }
export const COMMAND_EXAMPLES: readonly CommandExample[] = [
  { group: 'Routines', text: 'Wait for the search field', hint: 'Wait up to 15 seconds for one matching editable field; then continue' },
  {"group": "Routines", "text": "Search Wikipedia", "hint": "Ask for search words, then continue · useful as a routine step"},
  {"group": "Routines", "text": "Wait for the page to load", "hint": "Wait up to 15 seconds before the next command; stop if loading takes longer"},
  {"group": "Form editing", "text": "Fill the search box with black holes", "hint": "Replace the whole field; text is literal and does not submit", "variations": ["Replace the search field with black holes"]},
  {"group": "Form editing", "text": "Clear the search field", "hint": "Empty the entire named field", "variations": ["Empty the search box"]},
  {"group": "Form editing", "text": "Select all text", "hint": "Select text in the focused editable field only", "variations": ["Highlight all text"]},
  {"group": "Form editing", "text": "Delete selected text", "hint": "Delete the current field selection", "variations": ["Erase the selected text"]},
  {"group": "Form editing", "text": "Show form fields", "hint": "Number available fields without revealing their values", "variations": ["Number the fields"]},
  {"group": "Form editing", "text": "Next field", "hint": "Focus the next available form field", "variations": ["Go to the next field", "Previous field"]},
  {"group": "Form editing", "text": "Choose Canada from the Country dropdown", "hint": "Select the exact visible label in a native single-select dropdown"},
  {"group": "Form editing", "text": "Check the Remember me checkbox", "hint": "Set a native checkbox; checking it again leaves it checked", "variations": ["Tick Remember me", "Uncheck Remember me"]},
  {"group": "Organize tabs", "text": "Sort tabs by title", "hint": "Sort ungrouped tabs after existing groups; pinned tabs stay first", "variations": ["Sort tabs alphabetically", "Sort tabs by site"]},
  {"group": "Organize tabs", "text": "Ungroup these tabs", "hint": "Remove the highlighted or referenced tabs from their groups"},
  {"group": "Groups & workspaces", "text": "Make the Research group purple", "hint": "Change the named group’s color", "variations": ["Color Research group blue"]},
  {"group": "Groups & workspaces", "text": "Ungroup Research group", "hint": "Keep its tabs open while removing the group"},
  {"group": "Chrome pages", "text": "Open downloads", "hint": "Open Chrome’s Downloads page"},
  {"group": "Chrome pages", "text": "Open history", "hint": "Open Chrome’s History page without reading it into HandsFree"},
  {"group": "Chrome pages", "text": "Open bookmarks", "hint": "Open Chrome’s bookmark manager"},
  {"group": "Chrome pages", "text": "Open Chrome settings", "hint": "Open browser settings", "variations": ["Open extensions"]},

  {"group": "Everyday wording", "text": "Get rid of the YouTube tab", "hint": "Close a named tab without switching to it", "variations": ["Close out of the YouTube tab", "Would you mind closing the YouTube tab?"]},
  {"group": "Everyday wording", "text": "Pull up Gmail", "hint": "Open Gmail or reuse its existing tab", "variations": ["Head over to Gmail", "I would like you to open Gmail"]},
  {"group": "Everyday wording", "text": "Make this page bigger", "hint": "Increase page zoom", "variations": ["Make the text larger", "Increase the text size"]},
  {"group": "Everyday wording", "text": "Make a copy of this tab", "hint": "Duplicate the current tab", "variations": ["Clone this tab", "Open a copy of this tab"]},
  {"group": "Everyday wording", "text": "Turn the sound off on YouTube", "hint": "Mute the named tab", "variations": ["Make YouTube silent", "Quiet down YouTube"]},
  {"group": "Everyday wording", "text": "Bring the GitHub tab to the front", "hint": "Switch to a named tab", "variations": ["Focus on the GitHub tab", "Switch over to the GitHub tab"]},
  {"group": "Tab sets", "text": "Mute all pinned tabs", "hint": "Target pinned tabs in this window", "variations": ["Mute all tabs that are pinned"]},
  {"group": "Tab sets", "text": "Unmute all muted tabs across all windows", "hint": "Explicitly include every open window"},
  {"group": "Tab sets", "text": "Close tabs two through five", "hint": "Review a numbered range before closing", "variations": ["Close tabs 2 to 5"]},
  {"group": "Tab sets", "text": "Pin tabs two, four, and six", "hint": "Validate every requested position before changing tabs"},
  {"group": "Tab sets", "text": "Close all tabs except the Gmail tab", "hint": "Review a set while keeping one named tab", "variations": ["Keep only the Gmail tab open"]},
  {"group": "Tab sets", "text": "Show me my open tabs", "hint": "Choose from a list of tabs in this window", "variations": ["What’s open?", "Which tabs do I have?"]},
  {"group": "Tab positions", "text": "Go forward three tabs", "hint": "Jump by a count, wrapping within this window", "variations": ["Go back two tabs"]},
  {"group": "Tab positions", "text": "Close the second tab from the right", "hint": "Count from the right without activating the target"},
  {"group": "Tab positions", "text": "Move this tab three places to the left", "hint": "Move several places while respecting pinned boundaries"},
  {"group": "Tab positions", "text": "Switch back", "hint": "Return to the previous HandsFree target", "variations": ["Go back to the last tab"]},
  {"group": "Audio & media", "text": "Pause YouTube", "hint": "Control media in a named tab", "variations": ["Pause the video on YouTube", "On the YouTube tab, pause the video"]},
  {"group": "Audio & media", "text": "Rewind two minutes", "hint": "Seek backward by a spoken duration", "variations": ["Skip back thirty seconds"]},
  {"group": "Audio & media", "text": "Jump to one minute thirty seconds", "hint": "Seek to a specific playback position", "variations": ["Jump to 1:30"]},
  {"group": "Audio & media", "text": "Turn volume down by fifteen percent", "hint": "Adjust player volume by an amount", "variations": ["Lower the volume by fifteen percent"]},
  {"group": "Page controls", "text": "Zoom to one hundred twenty five percent", "hint": "Understand compound spoken numbers"},
  {"group": "Page controls", "text": "Type hello and welcome!", "hint": "Unquoted typing keeps the whole text literal"},
  {"group": "Page controls", "text": "Open link twenty one", "hint": "Compound spoken numbers work with link labels"},
  {"group": "Groups & workspaces", "text": "Put Gmail and GitHub in a group called Work", "hint": "Group a named set of tabs"},
  {"group": "Groups & workspaces", "text": "Save this session as Research", "hint": "Save a workspace using everyday session wording", "variations": ["Remember this window under the name Research"]},
  {"group": "Groups & workspaces", "text": "Load my Research workspace", "hint": "Restore a saved workspace", "variations": ["Reopen my Research session"]},
  { group: 'Sites & nicknames', text: 'Open Gmail', hint: 'Reuse an existing tab, or open the site if needed' },
  { group: 'Sites & nicknames', text: 'Open another Gmail tab', hint: 'Explicitly open one more tab' },
  { group: 'Sites & nicknames', text: 'Call this site my work dashboard', hint: 'Save a personal website nickname in Library' },
  { group: 'Sites & nicknames', text: 'Open my music', hint: 'Use the preferred app selected in Settings' },
  { group: 'Sites & nicknames', text: 'Add this site to my morning routine', hint: 'Add the current page to a saved macro' },
  { group: 'Site search', text: 'Search Amazon for headphones', hint: 'Search a supported site directly' },
  { group: 'Site search', text: 'Look up sourdough on Reddit', hint: 'Keep all query words together' },
  { group: 'Site search', text: 'Search Wikipedia for black holes', hint: 'Also supports other built-in sites and custom search URLs' },
  { group: 'Follow-ups & undo', text: 'Mute it', hint: 'Use the last targeted tab even after focus changes' },
  { group: 'Follow-ups & undo', text: 'Move that next to Gmail', hint: 'Place the referenced tab beside another tab' },
  { group: 'Follow-ups & undo', text: 'Mute Gmail and YouTube', hint: 'Apply one command to several named tabs' },
  { group: 'Follow-ups & undo', text: 'Close those two', hint: 'Review the two previously targeted tabs before closing' },
  { group: 'Follow-ups & undo', text: 'Undo that move', hint: 'Restore a move; pin, mute, and zoom also support undo' },
  { group: 'Audio & media', text: 'Which tab is making noise', hint: 'Find audible tabs across windows' },
  { group: 'Audio & media', text: 'Take me to the tab playing music', hint: 'Focus an audible tab; clarify if several are playing' },
  { group: 'Audio & media', text: 'Mute everything except this meeting', hint: 'Keep the current tab audible and mute the others' },
  { group: 'Audio & media', text: 'Pause this video', hint: 'Pause accessible page media · allow site access first' },
  { group: 'Audio & media', text: 'Go back ten seconds', hint: 'Seek within accessible audio or video' },
  { group: 'Audio & media', text: 'Set volume to 40 percent', hint: 'Change player volume rather than tab mute' },
  { group: 'Page controls', text: 'Scroll down a little', hint: 'Scroll the focused page or scrollable region' },
  { group: 'Page controls', text: 'Keep going', hint: 'Repeat the last scroll amount and direction' },
  { group: 'Page controls', text: 'Find pricing on this page', hint: 'Find visible text on the page' },
  { group: 'Page controls', text: 'Next match', hint: 'Move through page search matches' },
  { group: 'Page controls', text: 'Show links', hint: 'Label visible links and controls with numbers' },
  { group: 'Page controls', text: 'Open number five in a new tab', hint: 'Open the fifth numbered link' },
  { group: 'Page controls', text: 'Click the Pricing button', hint: 'Click an accessible label; ambiguous labels ask for a choice' },
  { group: 'Dictation', text: 'Type into the search box', hint: 'Focus an editable field · never submits it' },
  { group: 'Dictation', text: 'Start dictation', hint: 'While continuously listening, treat speech as literal text' },
  { group: 'Dictation', text: 'Stop dictation', hint: 'Return to browser commands' },
  { group: 'Groups & workspaces', text: 'Group these tabs as Research', hint: 'Group highlighted tabs or the last targeted set' },
  { group: 'Groups & workspaces', text: 'Collapse Research group', hint: 'Also expand, rename, or move a named group' },
  { group: 'Groups & workspaces', text: 'Move Research group to a new window', hint: 'Move a whole group into a fresh window' },
  { group: 'Groups & workspaces', text: 'Save this workspace as Work', hint: 'Save web tabs, pin states, and named groups locally' },
  { group: 'Groups & workspaces', text: 'Restore my work tabs', hint: 'Reopen a saved workspace in a new window' },
  { group: 'Reading & cleanup', text: 'Save this for later', hint: 'Add this page to Chrome’s reading list' },
  { group: 'Reading & cleanup', text: 'Open my unread articles', hint: 'Review the unread URLs before opening a batch' },
  { group: 'Reading & cleanup', text: 'Show duplicate tabs', hint: 'Review exact copies while keeping active and pinned tabs' },
  { group: 'Help', text: 'What can I say here', hint: 'Get suggestions for this page' },
  { group: 'Named tabs', text: 'Close the YouTube tab', hint: 'Close one tab by its title or website · no AI needed' },
  { group: 'Named tabs', text: 'Close tab containing design notes', hint: 'Use more title words if several tabs match' },
  { group: 'Named tabs', text: 'Switch to the GitHub tab', hint: 'Find a uniquely matching tab across windows' },
  { group: 'Named tabs', text: 'Mute the YouTube tab', hint: 'Also silence or unmute a named tab' },
  { group: 'Named tabs', text: 'Pin the Gmail tab', hint: 'Pin or unpin without switching to the tab' },
  { group: 'Named tabs', text: 'Reload the Calendar tab', hint: 'Also refresh or hard reload a named tab' },
  { group: 'Named tabs', text: 'Duplicate the Design tab', hint: 'Make another copy of a matching tab' },
  { group: 'Tab positions', text: 'Next tab', hint: 'Next or previous · wraps at either end of this window' },
  { group: 'Tab positions', text: 'Switch to the first tab', hint: 'First or last tab in this window' },
  { group: 'Tab positions', text: 'Switch to tab three', hint: 'Tab numbers count from the left, starting at 1' },
  { group: 'Tab positions', text: 'Close tab number three', hint: 'Close by position without activating it first' },
  { group: 'Tab positions', text: 'Mute tab two', hint: 'Numbers also work with pin, reload, and duplicate' },
  { group: 'Organize tabs', text: 'Move this tab left', hint: 'Move left or right within the tab strip' },
  { group: 'Organize tabs', text: 'Move the GitHub tab to the end', hint: 'Move a named tab · pinned tabs stay in their section' },
  { group: 'Organize tabs', text: 'Move this tab to position three', hint: 'Choose a specific position in this window' },
  { group: 'Organize tabs', text: 'Move this tab to a new window', hint: 'Detach this tab into its own window' },
  { group: 'Close & restore', text: 'Reopen the last closed tab', hint: 'Also “undo close” · restores one recently closed tab' },
  { group: 'Close & restore', text: 'Close all YouTube tabs', hint: 'Review first · matching tabs in this window only' },
  { group: 'Close & restore', text: 'Close tabs to the right', hint: 'Review before closing several tabs' },
  { group: 'Close & restore', text: 'Keep only this tab', hint: 'Review before closing the other tabs in this window' },
  { group: 'Close & restore', text: 'Close all tabs in this window', hint: 'Review first · the window closes when its last tab closes' },
  { group: 'Tabs & windows', text: 'Open a new tab', hint: 'Create a blank tab' },
  { group: 'Tabs & windows', text: 'Open a new window', hint: 'Create a normal Chrome window' },
  { group: 'Tabs & windows', text: 'Maximize this window', hint: 'Minimize, fullscreen, or restore' },
  { group: 'Tabs & windows', text: 'Mute this tab then pin this tab', hint: 'Join actions with “then” · executes in order' },
  { group: 'Search', text: 'Search Google for weekend hikes', hint: 'Search terms are kept together as one query' },
  { group: 'Search', text: 'Search YouTube for quiet piano', hint: 'YouTube search in a new tab' },
  { group: 'Search', text: 'Search GitHub for voice commands', hint: 'Search repositories and code on GitHub' },
  { group: 'Page', text: 'Zoom to 125 percent', hint: 'Zoom in, zoom out, or reset zoom' },
  { group: 'Page', text: 'Go back', hint: 'Move back or forward in this tab' },
  { group: 'Bookmarks', text: 'Bookmark this page', hint: 'Save the current page' },
  { group: 'Bookmarks', text: 'Bookmark this page as Recipes in Cooking', hint: 'Choose a bookmark title and folder' },
  { group: 'Bookmarks', text: 'Open bookmark recipes', hint: 'Find a saved page by name' },
];
