import type { AppState } from './types';
export interface DiagnosticCheck { title: string; status: 'ready' | 'attention' | 'info'; detail: string; action?: 'onboarding' | 'shortcuts' | 'settings' | 'sleep'; }
export function recoveryAdvice(error: string): DiagnosticCheck {
  if (/notallowed|denied|not-allowed|microphone.*permission|microphone access is blocked/i.test(error)) return { title: 'Microphone access', status: 'attention', detail: 'Open Microphone setup and allow access. If Chrome still blocks it, allow Chrome under your computer’s microphone privacy settings, then restart Chrome.', action: 'onboarding' };
  if (/notfound|no.*microphone|audio-capture|notreadable/i.test(error)) return { title: 'Microphone device', status: 'attention', detail: 'Connect a microphone, select the intended input in your computer’s sound settings, and close other apps using it. Run the microphone check again.', action: 'onboarding' };
  if (/permission|access to|restricted|internal page/i.test(error)) return { title: 'Website access', status: 'attention', detail: 'Open a regular website and use Settings → Page controls → Allow this site. Chrome’s internal pages cannot use page controls.', action: 'settings' };
  if (/network|connection|speech.*service/i.test(error)) return { title: 'Speech or network connection', status: 'attention', detail: 'Check your internet connection, stop listening, then start again. Chrome speech recognition can require internet; typed commands still work.', action: 'sleep' };
  if (/api|401|403|quota|model|key/i.test(error)) return { title: 'AI connection', status: 'attention', detail: 'Check your saved provider, model, and key in Settings, then use Test saved connection. Built-in commands work with AI off.', action: 'settings' };
  if (/engine|offscreen|timeout|respond/i.test(error)) return { title: 'Restart the voice engine', status: 'attention', detail: 'Release the engine below, then press your shortcut to start again. If the problem remains, reload HandsFree on chrome://extensions.', action: 'sleep' };
  return { title: 'Try a more specific command', status: 'info', detail: 'Use an example from Commands, name the target field or tab precisely, and check what completed in Control before retrying.' };
}
export function diagnosticsFor(state: AppState, siteAllowed: boolean, providerAllowed: boolean): DiagnosticCheck[] {
  const checks: DiagnosticCheck[] = [
    { title: 'Keyboard shortcut', status: state.shortcut ? 'ready' : 'attention', detail: state.shortcut ? `${state.shortcut} is assigned. Press it again to stop listening.` : 'No shortcut is assigned. Choose one that does not conflict with your other extensions.', action: 'shortcuts' },
    { title: 'Microphone setup', status: state.settings.micGranted ? 'info' : 'attention', detail: state.settings.micGranted ? 'Setup was completed previously. Run the visible microphone check to verify the device still works.' : 'Enable the microphone in setup, or continue using typed commands.', action: 'onboarding' },
    { title: 'First browser command', status: state.settings.setupCommandPassed ? 'ready' : 'info', detail: state.settings.setupCommandPassed ? 'The guided browser command has succeeded on this device.' : 'Try opening a practice tab in the setup guide.', action: 'onboarding' },
    { title: 'Voice engine', status: state.listening && !state.engineOpen ? 'attention' : 'ready', detail: state.listening ? state.engineOpen ? 'Listening. Use the shortcut or Stop listening to turn it off.' : 'The microphone session has lost its engine. Release it and start again.' : state.engineOpen ? 'Ready; the microphone is off.' : 'Asleep to save memory; starts when needed.', ...(state.engineOpen || state.listening ? { action: 'sleep' as const } : {}) },
    { title: 'Current website access', status: !state.activeSiteOrigin ? 'info' : siteAllowed ? 'ready' : 'attention', detail: !state.activeSiteOrigin ? 'Open a regular website to check page-control access.' : siteAllowed ? `Page access is allowed for ${new URL(state.activeSiteOrigin).hostname}.` : `No saved grant for ${new URL(state.activeSiteOrigin).hostname}. A temporary active-tab grant may work; allow this site in Settings for repeated page controls.`, action: 'settings' },
    { title: 'AI configuration', status: !state.settings.aiEnabled || state.settings.aiProvider === 'local' || (state.hasApiKey && providerAllowed) ? 'info' : 'attention', detail: !state.settings.aiEnabled ? 'AI is off. Commands and routines work locally without a key.' : state.settings.aiProvider === 'local' ? 'The experimental local model is selected. This check does not test its accuracy.' : !state.hasApiKey ? 'No saved key for this provider. Add one in Settings.' : !providerAllowed ? 'Access to the configured provider is missing. Save preferences to request it.' : 'A key and provider permission are present. This check makes no API request; use Test saved connection to test the provider.', action: 'settings' },
  ];
  if (state.hud.phase === 'error') checks.unshift(recoveryAdvice(state.hud.text));
  return checks;
}
