import type { Workspace } from './library';

export type WorkspaceNames = readonly Pick<Workspace, 'id' | 'name'>[];
export function workspaceDisplayName(value: string, workspaces: WorkspaceNames = []): string {
  return workspaces.find(workspace => workspace.id === value)?.name ?? value;
}
/** Display only the exact command forms generated by Library controls.
 * The original transcript remains available for editing and execution. */
export function workspaceDisplayTranscript(text: string, workspaces: WorkspaceNames = []): string {
  const match = text.match(/^((?:recover|rename|restore) )([0-9a-f-]{36})( workspace)$/i)
    ?? text.match(/^(update )([0-9a-f-]{36})( workspace from this window)$/i)
    ?? text.match(/^(discard previous version of )([0-9a-f-]{36})( workspace)$/i);
  if (!match) return text;
  const name = workspaceDisplayName(match[2]!, workspaces);
  return `${match[1]}${name}${match[3]}`;
}
